enum MicroKeyAction {
  unknown,
  reset,
  kb,
  f1,
  insert,
  f2,
  delete,
  next,
  prev,
  c,
  d,
  e,
  f,
  num8,
  num9,
  a,
  b,
  num4,
  num5,
  num6,
  num7,
  num0,
  num1,
  num2,
  num3,
  outByte,
  inByte,
  singleStep,
  blkMove,
  examReg,
  examMem,
  go,
  exec,
}

const ksMicroKeyAction = <MicroKeyAction, String>{
  MicroKeyAction.reset: "RESET",
  MicroKeyAction.kb: "KB\nINT",
  MicroKeyAction.f1: "F1",
  MicroKeyAction.insert: "INSERT",
  MicroKeyAction.f2: "F2",
  MicroKeyAction.delete: "DELETE",
  MicroKeyAction.next: "NEXT",
  MicroKeyAction.prev: "PREV",
  MicroKeyAction.c: "C",
  MicroKeyAction.d: "D",
  MicroKeyAction.e: "E",
  MicroKeyAction.f: "F",
  MicroKeyAction.num8: "8",
  MicroKeyAction.num9: "9",
  MicroKeyAction.a: "A",
  MicroKeyAction.b: "B",
  MicroKeyAction.num4: "4",
  MicroKeyAction.num5: "5",
  MicroKeyAction.num6: "6",
  MicroKeyAction.num7: "7",
  MicroKeyAction.num0: "0",
  MicroKeyAction.num1: "1",
  MicroKeyAction.num2: "2",
  MicroKeyAction.num3: "3",
  MicroKeyAction.outByte: "OUT\nBYTE",
  MicroKeyAction.inByte: "IN\nBYTE",
  MicroKeyAction.singleStep: "SINGLE\nSTEP",
  MicroKeyAction.blkMove: "BLK\nMOVE",
  MicroKeyAction.examReg: "EXAM\nREG",
  MicroKeyAction.examMem: "EXAM\nMEM",
  MicroKeyAction.go: "GO",
  MicroKeyAction.exec: "EXEC",
};
